// Generated by node build.js. Edit the source modules, then rebuild.
(()=>{
"use strict";
// Source: economy.js
// September 2026 neighbourhood-stand estimates; values are integer minor units.
const ECONOMIES = Object.freeze(Object.fromEntries(Object.entries({
  GBP: { symbol:'£', minor:'p', region:'United Kingdom', startingCash:2000, glassCosts:[25,30,35], signCost:50, referencePrice:150 },
  USD: { symbol:'$', minor:'¢', region:'United States', startingCash:2500, glassCosts:[35,40,50], signCost:75, referencePrice:200 },
  EUR: { symbol:'€', minor:'¢', region:'Euro area', startingCash:2200, glassCosts:[30,35,40], signCost:60, referencePrice:175 },
  CAD: { symbol:'$', minor:'¢', region:'Canada', startingCash:3500, glassCosts:[45,55,65], signCost:100, referencePrice:250 },
  AUD: { symbol:'$', minor:'¢', region:'Australia', startingCash:4000, glassCosts:[50,60,75], signCost:120, referencePrice:300 },
}).map(([currency, values]) => [currency, Object.freeze({ ...values, currency, glassCosts:Object.freeze(values.glassCosts), maxPrice:values.referencePrice*10 })])));
function economyFor(currency='GBP') {
  if (!Object.hasOwn(ECONOMIES, currency)) throw new Error('Unsupported currency.');
  return ECONOMIES[currency];
}
function formatMoney(amount, currency='GBP') {
  if (!Number.isSafeInteger(amount)) return '—';
  const {symbol,minor} = economyFor(currency), absolute = Math.abs(amount), sign = amount < 0 ? '-' : '';
  if (absolute < 100) return `${sign}${absolute}${minor}`;
  return `${sign}${symbol}${(absolute/100).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
}
function parseMoney(input, currency='GBP') {
  const {symbol,minor} = economyFor(currency);
  let value = String(input).trim();
  if (value.endsWith(minor)) { value=value.slice(0,-1).trim(); return /^\d+$/.test(value) && Number.isSafeInteger(Number(value)) ? Number(value) : NaN; }
  if (value.startsWith(symbol)) value=value.slice(symbol.length).trim();
  if (!/^(?:\d+|\d{1,3}(?:,\d{3})+)?(?:\.\d{1,2})?$/.test(value) || !/\d/.test(value)) return NaN;
  const [whole='0',fraction=''] = value.replaceAll(',','').split('.');
  const amount=Number(whole)*100+Number(fraction.padEnd(2,'0'));
  return Number.isSafeInteger(amount) ? amount : NaN;
}

// Source: engine.js
// Apple II demand and events, with currency-specific contemporary prices.

const DAYS = 14;
const glassCost = (day, economy=economyFor()) => economy.glassCosts[day > 6 ? 2 : day > 2 ? 1 : 0];
function createGame(names, currency='GBP') {
  if (!Array.isArray(names) || names.length < 2 || names.length > 8 || Array.from(names).some(name=>typeof name !== 'string' || !name.trim() || name.trim().length > 24)) throw new Error('Enter 2 to 8 names, up to 24 characters each.');
  names = names.map(name=>name.trim());
  if (new Set(names.map(name=>name.toLocaleLowerCase())).size !== names.length) throw new Error('Choose different player names.');
  const economy = economyFor(currency);
  return { day: 1, currency, economy, players: names.map(name => ({ name, cash: economy.startingCash, bankrupt: false, sold: 0, revenue: 0, expenses: 0 })), history: [] };
}
function forecast(day, random = Math.random, history = []) {
  // Requested house rules: opening days are clear or hot, and never three
  // identical forecasts consecutively. Reweight eligible choices, without retries.
  const previous=history.slice(-2).map(entry=>entry.weather?.type ?? entry.type ?? entry);
  const blocked=previous.length===2 && previous[0]===previous[1] ? previous[0] : null;
  const choices=[['sunny',.6],['cloudy',.2],['hot',.2]].filter(([type])=>type!==blocked && (day>3 || type!=='cloudy'));
  let roll=random()*choices.reduce((total,[,weight])=>total+weight,0);
  let type=choices.at(-1)[0];
  for(const [candidate,weight] of choices){if(roll<weight){type=candidate;break;}roll-=weight;}
  const weather = { type, factor: 1, roadworks: false, crewBuyout: false, rainChance: 0 };
  if (type === 'cloudy') { weather.rainChance = 30 + Math.floor(random() * 5) * 10; weather.factor = 1 - weather.rainChance / 100; }
  else if (type === 'hot') weather.factor = 2;
  else if (day > 2 && random() < .25) { weather.roadworks = true; weather.crewBuyout = random() >= .5; weather.factor = weather.crewBuyout ? 1 : .1; }
  return weather;
}
function validatePlan(plan, cash, day, economy=economyFor()) {
  if (!plan || typeof plan !== 'object') return 'Enter a plan for every stand.';
  for (const [key, max] of [['glasses', 1000], ['signs', 50], ['price', economy.maxPrice]]) {
    if (!Number.isInteger(plan[key]) || plan[key] < 0 || plan[key] > max) return `Enter a whole number from 0 to ${max} for ${key}.`;
  }
  if (plan.glasses * glassCost(day,economy) + plan.signs * economy.signCost > cash) return 'That costs more than you have. Make fewer glasses or signs.';
  return '';
}
function customerDemand(price, signs, factor, referencePrice=150) {
  const base = price < referencePrice ? (referencePrice-price)/referencePrice*.8*30+30 : referencePrice**2*30/(price*price);
  return Math.floor(factor * base * (2 - Math.exp(-signs * .5)));
}
function settleDay(game, plans, weather, random = Math.random) {
  if (game.day > DAYS || game.history.length !== game.day - 1) throw new Error('This day has already been settled.');
  if (!Array.isArray(plans) || plans.length !== game.players.length || Array.from(plans).some(plan=>!plan)) throw new Error('Every player must submit a plan.');
  const economy = game.economy;
  plans.forEach((plan, i) => { if (!game.players[i].bankrupt) { const error = validatePlan(plan, game.players[i].cash, game.day,economy); if (error) throw new Error(error); } });
  const storm = weather.type === 'cloudy' && random() < .25;
  const rows = game.players.map((player, i) => {
    const plan = player.bankrupt ? { glasses: 0, signs: 0, price: 0 } : plans[i];
    const sold = storm ? 0 : weather.crewBuyout ? plan.glasses : Math.min(plan.glasses, customerDemand(plan.price, plan.signs, weather.factor,economy.referencePrice));
    const expenses = plan.glasses * glassCost(game.day,economy) + plan.signs * economy.signCost;
    const revenue = sold * plan.price;
    const profit = revenue - expenses;
    player.cash += profit;
    player.sold += sold; player.revenue += revenue; player.expenses += expenses;
    // Preserve the original post-report <= current glass-cost bankruptcy check.
    player.bankrupt ||= player.cash <= glassCost(game.day,economy);
    return { ...plan, sold, unsold: plan.glasses - sold, expenses, revenue, profit, cash: player.cash, bankrupt: player.bankrupt };
  });
  const report = { day: game.day, weather: { ...weather }, storm, rows };
  game.history.push(report);
  return report;
}

// Source: audio.js
// Apple II DATA 11530–11560, decoded using the 6502 speaker-delay loop.
// https://gist.github.com/mreider/c7cf24ee3cccd509f76217154af2ae49
const WEATHER_DATA = Object.freeze({
  sunny: [[96,16],[85,4],[128,4],[96,4],[76,4],[128,4],[96,16]],
  hot: [[114,120],[144,60],[114,255],[1,120],[128,120],[144,60],[128,120],[114,60],[144,120],[171,255],[228,255]],
  cloudy: [[152,180],[152,120],[152,60],[144,120],[152,60],[171,120],[192,60],[152,255]],
  storm: [[0,160],[128,255],[152,40],[171,80],[192,40],[228,255],[1,40],[0,160],[192,255],[192,40],[171,80],[152,40],[128,255]],
});
// Daily financial report: original POKE/CALL sequence at BASIC lines 1140–1148.
const REPORT_DATA = Object.freeze([[152,80],[128,160],[152,40],[144,80],[128,200]]);
const CLOCK=1023000;
function weatherNotes(type) {
  return (type==='report' ? REPORT_DATA : WEATHER_DATA[type] || WEATHER_DATA.sunny).map(([delay,length]) => ({
    frequency: delay===1 ? 0 : CLOCK/(2*(10*(delay || 256)+14)),
    // Sunny repeats short calls; other tracks use the high-byte note duration.
    duration: type==='sunny' ? length*.075 : length*256*10.08/CLOCK,
  }));
}
function themeDuration(type) { return weatherNotes(type).reduce((sum,n)=>sum+n.duration,0)+.1; }
class WeatherMusic {
  constructor() { this.enabled=true; this.context=null; this.voices=[]; this.playback=null; }
  async unlock() {
    let timeout;
    try { this.context ??= new (window.AudioContext || window.webkitAudioContext)(); await Promise.race([this.context.resume(),new Promise(resolve=>{timeout=setTimeout(resolve,1200);})]); } catch { /* Audio is optional; the timed report still runs. */ }
    finally {clearTimeout(timeout);}
  }
  stop(clearPlayback=true) {
    for (const voice of this.voices) { try { voice.oscillator.stop(); } catch {} voice.oscillator.disconnect(); voice.gain.disconnect(); }
    this.voices=[]; if(clearPlayback) this.playback=null;
  }
  setEnabled(enabled) {
    this.enabled=enabled;
    if(!enabled) this.stop(false);
    else if(this.playback && this.context) this.schedule(this.playback.type,Math.max(0,this.context.currentTime-this.playback.start));
  }
  play(type) {
    this.stop();
    if(this.context) this.playback={type,start:this.context.currentTime};
    if(this.enabled) this.schedule(type,0);
    return themeDuration(type);
  }
  schedule(type,offset) {
    this.stop(false);
    // Scheduling in a suspended context is safe: notes wait for resume, which
    // keeps a report opened in a hidden tab aligned with its paused reveal.
    if(!this.context || this.context.state==='closed') return;
    if(type==='storm'){this.scheduleStorm(offset);return;}
    let elapsed=0;
    for(const note of weatherNotes(type)) {
      const end=elapsed+note.duration;
      if(end>offset && note.frequency) {
        const start=this.context.currentTime+Math.max(0,elapsed-offset)+.02, duration=end-Math.max(elapsed,offset);
        if(duration < .012) { elapsed=end; continue; }
        const oscillator=this.context.createOscillator(),gain=this.context.createGain();
        // Single-voice square wave with softened edges; no added bass or harmony.
        oscillator.type='square'; oscillator.frequency.value=note.frequency;
        gain.gain.setValueAtTime(0,start); gain.gain.linearRampToValueAtTime(.045,start+.004);
        gain.gain.setValueAtTime(.045,start+duration-.008); gain.gain.linearRampToValueAtTime(0,start+duration);
        oscillator.connect(gain);gain.connect(this.context.destination);oscillator.start(start);oscillator.stop(start+duration+.01);
        const voice={oscillator,gain};this.voices.push(voice);
        oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();this.voices=this.voices.filter(v=>v!==voice);};
      }
      elapsed=end;
    }
  }
  scheduleStorm(offset) {
    // One continuous, softer voice preserves the original tune without resetting
    // oscillator phase and chopping the envelope at every short note.
    const notes=weatherNotes('storm'),total=notes.reduce((sum,n)=>sum+n.duration,0);
    if(total-offset<.03)return;
    const oscillator=this.context.createOscillator(),gain=this.context.createGain();
    const start=this.context.currentTime+.02,level=.085;
    oscillator.type='triangle';gain.gain.setValueAtTime(0,start);
    let elapsed=0,first=true,sounding=false;
    for(const note of notes){
      const end=elapsed+note.duration;
      if(end>offset){
        const at=start+Math.max(0,elapsed-offset),until=start+end-offset;
        if(note.frequency){
          if(first)oscillator.frequency.setValueAtTime(note.frequency,at);
          else oscillator.frequency.linearRampToValueAtTime(note.frequency,at+.008);
          // Hold pitch through each note, with a short transition at the next.
          oscillator.frequency.setValueAtTime(note.frequency,until);
          if(!sounding)gain.gain.linearRampToValueAtTime(level,at+Math.min(.012,(until-at)/2));
          sounding=true;
        }else{
          gain.gain.setValueAtTime(level,Math.max(start,at-.012));
          gain.gain.linearRampToValueAtTime(0,at);sounding=false;
        }
        first=false;
      }
      elapsed=end;
    }
    const end=start+total-offset;
    gain.gain.setValueAtTime(level,end-.025);gain.gain.linearRampToValueAtTime(0,end);
    oscillator.connect(gain);gain.connect(this.context.destination);oscillator.start(start);oscillator.stop(end+.01);
    const voice={oscillator,gain};this.voices.push(voice);
    oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();this.voices=this.voices.filter(v=>v!==voice);};
  }
  async pause() { try { await this.context?.suspend(); } catch {} }
  async resume() { try { await this.context?.resume(); } catch {} }
}

// Source: weather-gate.js
// Counts foreground viewing time, independent of mute and unavailable audio.
class WeatherGate {
  constructor(duration, now=performance.now()) { this.remaining=duration; this.last=now; this.paused=false; }
  update(now=performance.now()) { if (!this.paused) this.remaining=Math.max(0,this.remaining-Math.max(0,now-this.last)); this.last=now; return this.remaining; }
  pause(now=performance.now()) { this.update(now); this.paused=true; }
  resume(now=performance.now()) { this.last=now; this.paused=false; }
  ready(now=performance.now()) { return this.update(now)===0; }
}

// Source: language.js
// Player-facing copy supplied by Fraise Aurora, with UK/US place and word choices.
const LANGUAGES = Object.freeze({
  'en-GB': { town:'Lemonshire', region:'England', mum:'mum', roadworks:'Roadworks' },
  'en-US': { town:'Lemonsville', region:'California', mum:'mom', roadworks:'Roadwork' },
});
function languageFor(code='en-GB') { return LANGUAGES[code] || LANGUAGES['en-GB']; }
function joinNames(names) {
  if(names.length<3)return names.join(' and ');
  return `${names.slice(0,-1).join(', ')}, and ${names.at(-1)}`;
}
function instructionPages(words, money, economy) {
  return [
    `<p>To manage your lemonade stand, you will need to make these decisions every day:</p><ol class="rules-list"><li>How many glasses of lemonade to make (only one batch is made each morning).</li><li>How many advertising signs to make (the signs cost ${money(economy.signCost)} each).</li><li>What price to charge for each glass.</li></ol><p>You will begin with <strong>${money(economy.startingCash)}</strong> cash (assets).</p><p>Because your ${words.mum} gave you some sugar, your cost to make lemonade is <strong>${money(economy.glassCosts[0])}</strong> a glass (this may change in the future).</p>`,
    `<p>Your expenses are the sum of the cost of the lemonade and the cost of the signs.</p><p>Your profits are the difference between the income from sales and your expenses.</p><p>The number of glasses you sell each day depends on the price you charge and on the number of advertising signs you use.</p><p>Keep track of your assets, because you can't spend more money than you have!</p>`,
  ];
}

// Source: game-source.js





const $=selector=>document.querySelector(selector);
const screen=$('#screen'),gameBox=$('#game'),music=new WeatherMusic();
let currency='GBP',language='en-GB',phase='title',game=null,weather=null,report=null;
let playerCount=2,draftNames=[],playerIndex=0,reportIndex=0,plans=[],currentPlan={};
let gate=null,timer=null,generation=0,leaveGuard=false;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>formatMoney(value,currency),words=()=>languageFor(language);
const economy=()=>game?.economy||economyFor(currency),cost=()=>glassCost(game?.day||1,economy());
const isWeather=()=>phase==='weather'||phase==='storm';
const arrow='<span aria-hidden="true">↗</span>';
const weatherNames={sunny:'Sunny',cloudy:'Cloudy',hot:'Hot and dry',storm:'Thunderstorms!'};
const weatherIcons={sunny:'☀',cloudy:'☁',hot:'☀',storm:'ϟ'};
function stopTimer(){clearInterval(timer);timer=null;gate=null;}
function beforeLeave(event){event.preventDefault();event.returnValue='';}
function syncLeaveGuard(){
  const needed=!!game && phase!=='results';
  if(needed===leaveGuard)return;
  window[needed?'addEventListener':'removeEventListener']('beforeunload',beforeLeave);
  leaveGuard=needed;
}
function setPhase(next){
  phase=next;render();screen.scrollTop=0;
  const heading=screen.querySelector('h1,h2');
  if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}
}
function resetGame(){
  generation++;stopTimer();music.stop();game=null;weather=null;report=null;plans=[];draftNames=[];playerCount=2;playerIndex=0;reportIndex=0;currentPlan={};
  $('#help-dialog').close();$('#restart-dialog').close();setPhase('title');
}
function button(id,text){return `<button id="${id}" class="primary">${text} ${arrow}</button>`;}
function rulesMarkup(){return instructionPages(words(),money,economy()).join('');}
function scores(){return `<div class="score-strip">${game.players.map((p,i)=>`<div class="score-chip"><small>Stand ${i+1} · ${escape(p.name)}</small><strong>${money(p.cash)}</strong></div>`).join('')}</div>`;}
function tradingCopy(){return `<section class="scene-copy trading-copy"><span class="eyebrow">DAY ${game.day} · ${words().town.toUpperCase()}</span><h1>Your lemonade<br><em>stand.</em></h1>${scores()}</section>`;}
function notices(){
  const items=[];
  if(game.day===3)items.push(`Your ${words().mum} quit giving you free sugar. Review the revised cost of lemonade.`);
  if(game.day===7)items.push('The price of lemonade mix just went up. Review the revised cost of lemonade.');
  if(weather.roadworks)items.push('The street department is working today. There will be no traffic on your street.');
  return items.map(text=>`<div class="notice">${text}</div>`).join('');
}
async function startWeather(storm=false){
  if(isWeather())return;
  stopTimer();music.stop();
  if(!storm && !weather)weather=forecast(game.day,Math.random,game.history);
  const type=storm?'storm':weather.type,run=generation;
  gate=new WeatherGate(Math.max(storm?7200:5000,(themeDuration(type)+.7)*1000));gate.pause();
  const thisGate=gate;setPhase(storm?'storm':'weather');
  await music.unlock();
  if(run!==generation || gate!==thisGate || !isWeather())return;
  music.play(type);if(document.hidden)void music.pause();else gate.resume();
  gameBox.setAttribute('data-weather-paused',String(document.hidden));
  timer=setInterval(updateWeather,100);updateWeather();
}
function updateWeather(){
  if(!isWeather()||!gate)return;
  const remaining=gate.update(),next=$('#weather-continue');if(!next)return;
  next.disabled=remaining>0;
  next.textContent=remaining>0?`Weather report · ${Math.ceil(remaining/1000)}s`:(phase==='storm'?'See the financial reports':'Continue');
  $('#weather-status').textContent=remaining>0?'Please watch the full report.':'Weather report complete.';
  if(!remaining){clearInterval(timer);timer=null;}
}
function renderWeather(){
  const type=phase==='storm'?'storm':weather.type;
  const descriptions={sunny:`Clear skies over ${words().town}.`,cloudy:`Cooler weather today, with a ${weather.rainChance}% chance of light rain.`,hot:'A heat wave is predicted for today!',storm:`A severe thunderstorm struck ${words().town} while the stands were being set up. All the lemonade was ruined.`};
  screen.innerHTML=`<section class="weather-card"><span class="eyebrow">${words().town.toUpperCase()} WEATHER REPORT</span><span class="weather-symbol" aria-hidden="true">${weatherIcons[type]}</span><h1>${weatherNames[type]}</h1><p>${descriptions[type]}</p><div class="weather-wait"><span id="weather-status" role="status">Please watch the full report.</span><button id="weather-continue" class="primary" disabled>Weather report</button></div></section>`;
  $('#weather-continue').onclick=()=>{if(!gate?.ready())return;const storm=phase==='storm';stopTimer();music.stop();if(storm)beginReport(0);else setPhase('costs');};
  updateWeather();
}
function render(){
  const backdrop=!game||phase==='rules-one'||phase==='rules-two'||phase==='results'?'sunny':phase==='storm'||report?.storm?'storm':weather?.type||'sunny';
  gameBox.className=`game phase-${phase} ${backdrop}`;
  gameBox.setAttribute('data-weather-paused',String(!!gate?.paused));
  document.documentElement.lang=language;
  $('#location').textContent=`${words().town.toUpperCase()} · ${words().region.toUpperCase()}`;
  $('#currency').disabled=!!game;$('#language').disabled=phase!=='title';
  for(const [id,locked] of [['currency',!!game],['language',phase!=='title']]){
    const label=id[0].toUpperCase()+id.slice(1),tip=locked?`${label} is locked. Start a new game to change it.`:`Choose your ${id}.`;
    $(`#${id}-control`).title=tip;$(`#${id}-control`).setAttribute('data-locked',String(locked));
    $(`#${id}-control`).setAttribute('tabindex',locked?'0':'-1');$(`#${id}-tooltip`).textContent=tip;$(`#${id}`).title=tip;
  }
  $('#help').disabled=isWeather();
  $('#day-label').textContent=game?`DAY ${String(game.day).padStart(2,'0')} / ${DAYS}`:'A LITTLE SUMMER RIVALRY';
  $('#progress-label').textContent=game?`${game.history.length} OF ${DAYS} DAYS COMPLETE`:'2–8 PLAYERS · 14 DAYS';
  $('#footer-hint').textContent=isWeather()?`${words().town} Weather Service`:'A classic, freshly squeezed.';
  syncLeaveGuard();
  if(phase==='title'){
    screen.innerHTML=`<section class="title-card"><span class="eyebrow">FOURTEEN DAYS IN ${words().town.toUpperCase()}</span><div class="title-lemon" aria-hidden="true"><img src="./lemon.svg" alt=""></div><h1>Lemonade<br><em>Stand.</em></h1><p>The classic summer business.<br>A fresh squeeze of friendly competition.</p>${button('start','Start')}<span class="title-details">2–8 PLAYERS <i>·</i> ONE DEVICE <i>·</i> 14 DAYS</span></section>`;
    $('#start').onclick=()=>setPhase('welcome');
  }else if(phase==='welcome'){
    screen.innerHTML=`<section class="wide-screen welcome-screen"><span class="eyebrow">WELCOME TO YOUR SUMMER JOB</span><h1>Hi! Welcome to ${words().town}, ${words().region}!</h1><p>In this small town, you are in charge of running your own lemonade stand. You can compete with as many other people as you wish, but how much profit you make is up to you (the other stands' sales will not affect your business in any way). If you make the most money, you're the winner!</p><h2>Begin a new game?</h2>${button('begin','Begin')}</section>`;
    $('#begin').onclick=()=>setPhase('players');
  }else if(phase==='players'){
    screen.innerHTML=`<section class="wide-screen setup-screen"><span class="eyebrow">YOUR SUMMER RIVALS</span><h1>How many people will be playing?</h1><form id="players-form"><label for="player-count">Number of players (2–8)</label><input id="player-count" type="number" min="2" max="8" step="1" required value="${playerCount}"><p class="error" id="count-error" aria-live="polite"></p>${button('choose-players','Continue')}</form></section>`;
    $('#players-form').onsubmit=event=>{event.preventDefault();const count=Number($('#player-count').value);if(!Number.isInteger(count)||count<2||count>8){$('#count-error').textContent='Choose between 2 and 8 players.';return;}playerCount=count;draftNames=Array.from({length:count},(_,i)=>draftNames[i]||'');setPhase('names');};
  }else if(phase==='names'){
    screen.innerHTML=`<section class="wide-screen setup-screen"><span class="eyebrow">${playerCount} STANDS · 14 DAYS</span><h1>Who will be playing?</h1><form id="setup-form"><div class="name-grid">${draftNames.map((name,i)=>`<label class="player-field" for="player-${i+1}"><span>Player ${i+1}</span><input id="player-${i+1}" type="text" maxlength="24" required autocomplete="off" value="${escape(name)}"></label>`).join('')}</div><p id="name-error" class="error" aria-live="polite"></p>${button('save-names','Continue')}</form><button id="change-count" class="small-button">Change the number of players</button></section>`;
    $('#setup-form').oninput=()=>{draftNames=draftNames.map((_,i)=>$(`#player-${i+1}`).value);};
    $('#setup-form').onsubmit=event=>{event.preventDefault();const names=draftNames.map((_,i)=>$(`#player-${i+1}`).value.trim());try{game=createGame(names,currency);}catch(error){$('#name-error').textContent=error.message;return;}draftNames=names;weather=null;report=null;plans=[];setPhase('rules-one');};
    $('#change-count').onclick=()=>setPhase('players');
  }else if(phase==='rules-one'||phase==='rules-two'){
    const first=phase==='rules-one';
    screen.innerHTML=`<section class="wide-screen rules-screen"><span class="eyebrow">HOW TO RUN YOUR STAND · ${first?'1':'2'} / 2</span><h2>${first?'Your daily decisions':'Your business accounts'}</h2>${instructionPages(words(),money,economy())[first?0:1]}${button('rules-continue','Continue')}</section>`;
    $('#rules-continue').onclick=()=>first?setPhase('rules-two'):startWeather();
  }else if(isWeather())renderWeather();
  else if(phase==='costs'){
    screen.innerHTML=`${tradingCopy()}<section class="panel"><span class="eyebrow">BEFORE YOU OPEN</span><h2>Day ${game.day}</h2><p>On day ${game.day}, the cost of lemonade is <strong>${money(cost())}</strong> a glass.</p><div class="cost-row"><span>One advertising sign</span><strong>${money(economy().signCost)}</strong></div>${notices()}${button('begin-turn','Make your decisions')}</section>`;
    $('#begin-turn').onclick=()=>{playerIndex=0;plans=[];beginPlan();};
  }else if(phase==='planning')renderPlan();
  else if(phase==='handoff'){
    screen.innerHTML=`${tradingCopy()}<section class="panel"><span class="eyebrow">PASS THE DEVICE</span><h2>${escape(game.players[playerIndex].name)}'s stand</h2><p>${escape(game.players[playerIndex-1].name)}'s decisions are saved.</p>${button('take-turn','I’m ready')}</section>`;
    $('#take-turn').onclick=beginPlan;
  }else if(phase==='report-wait'||phase==='report')renderReport();
  else if(phase==='results')renderResults();
}
function renderPlan(){
  const player=game.players[playerIndex],last=playerIndex===game.players.length-1;
  screen.innerHTML=`${tradingCopy()}<section class="panel planning"><span class="eyebrow">STAND ${playerIndex+1} OF ${game.players.length}</span><h2>${escape(player.name)}'s stand</h2><div class="turn-line">Assets <strong>${money(player.cash)}</strong></div>${player.bankrupt?`<p>You are bankrupt. No decisions for you to make.</p>${button('skip-turn','Continue')}`:`<form id="plan-form">${inputRow('glasses','Glasses of lemonade to make',`${money(cost())} per glass`,1000)}${inputRow('signs','Advertising signs to make',`${money(economy().signCost)} per sign`,50)}${inputRow('price','Price to charge per glass',`e.g. ${money(economy().referencePrice)} or ${money(50)}`,economy().maxPrice)}<div class="budget"><div class="money-row"><span>Expenses</span><strong id="spending"></strong></div><div class="money-row"><span>Assets left before sales</span><strong id="remaining"></strong></div></div><p id="plan-error" class="error" aria-live="polite"></p>${button('submit-plan',last?'Open all stands':'Save & pass to the next player')}</form><p class="fine-print">Your decisions stay hidden until every stand is ready.</p>`}</section>`;
  if(player.bankrupt){$('#skip-turn').onclick=()=>commitPlan({glasses:0,signs:0,price:0});return;}
  $('#plan-form').oninput=updateBudget;
  screen.querySelectorAll('[data-step]').forEach(control=>{control.onclick=()=>{const input=document.getElementById(control.dataset.target),price=input.id==='price';const old=price?parseMoney(input.value,currency):Number(input.value);const value=Math.max(0,Math.min(price?economy().maxPrice:Number(input.max),(Number.isFinite(old)?old:0)+Number(control.dataset.step)));input.value=price?money(value):value;updateBudget();};});
  $('#plan-form').onsubmit=event=>{event.preventDefault();updateBudget();if(!validatePlan(currentPlan,player.cash,game.day,economy()))commitPlan({...currentPlan});};
  updateBudget();
}
function inputRow(id,title,note,max){const price=id==='price';return `<div class="entry-row"><label for="${id}">${title}<small>${note}</small></label><div class="number-control ${price?'price-control':''}"><button type="button" data-target="${id}" data-step="${price?-5:-1}" aria-label="Decrease ${title.toLowerCase()}">−</button><input id="${id}" type="${price?'text':'number'}" ${price?'':`min="0" max="${max}" step="1"`} inputmode="${price?'decimal':'numeric'}" required autocomplete="off" value=""><button type="button" data-target="${id}" data-step="${price?5:1}" aria-label="Increase ${title.toLowerCase()}">+</button></div></div>`;}
function beginPlan(){currentPlan={};setPhase('planning');}
function updateBudget(){
  currentPlan=Object.fromEntries(['glasses','signs'].map(key=>[key,$(`#${key}`).value===''?NaN:Number($(`#${key}`).value)]));currentPlan.price=parseMoney($('#price').value,currency);
  const spent=currentPlan.glasses*cost()+currentPlan.signs*economy().signCost,remaining=game.players[playerIndex].cash-spent;
  $('#spending').textContent=money(spent);$('#remaining').textContent=money(remaining);$('#remaining').className=remaining<0?'negative':'';
  const error=validatePlan(currentPlan,game.players[playerIndex].cash,game.day,economy());
  const incomplete=['glasses','signs','price'].some(id=>$(`#${id}`).value==='');
  $('#plan-error').textContent=incomplete?'':error && (!Number.isInteger(currentPlan.price)||currentPlan.price>economy().maxPrice)?`Enter a price from ${money(0)} to ${money(economy().maxPrice)}.`:error;
  $('#submit-plan').disabled=!!error;
}
function commitPlan(plan){
  if(phase!=='planning'||plans[playerIndex])return;
  plans[playerIndex]=plan;
  if(playerIndex<game.players.length-1){playerIndex++;setPhase('handoff');}
  else{report=settleDay(game,plans,weather);if(report.storm)void startWeather(true);else beginReport(0);}
}
function beginReport(index){
  stopTimer();music.stop();reportIndex=index;
  // The original report cue plays once per day, before the first stand's figures.
  gate=new WeatherGate(index===0?Math.max(2000,themeDuration('report')*1000):2000);
  if(document.hidden)gate.pause();setPhase('report-wait');
  if(index===0)music.play('report');
  timer=setInterval(updateReport,50);
}
function updateReport(){if(phase==='report-wait'&&gate?.ready()){stopTimer();music.stop();setPhase('report');}}
function renderReport(){
  const row=report.rows[reportIndex],player=game.players[reportIndex],last=reportIndex===game.players.length-1;
  const title=`${words().town} Daily Financial Report`;
  if(phase==='report-wait'){
    screen.innerHTML=`<section class="wide-screen stand-report"><h2>${title}</h2><p class="report-loading" role="status">Preparing ${escape(player.name)}'s report…</p><div class="report-loader" aria-hidden="true"></div></section>`;return;
  }
  const note=report.storm?'A thunderstorm ruined all the lemonade. No sales today.':weather.crewBuyout?'The street crews bought all your lemonade at lunchtime!':weather.roadworks?`${words().roadworks} kept passing traffic away.`:'';
  screen.innerHTML=`<section class="wide-screen stand-report"><h2>${title}</h2><p class="report-stand">Day ${game.day} <span>│</span> Stand ${reportIndex+1} · ${escape(player.name)}</p>${note?`<p class="report-note">${note}</p>`:''}<div class="stand-numbers"><div><p><strong>${row.sold}</strong> glasses sold</p><p><strong>${money(row.price)}</strong> per glass</p></div><div><p><strong>${row.glasses}</strong> glasses made</p><p><strong>${row.signs}</strong> signs made</p></div></div><div class="report-accounts"><p>Income: <strong>${money(row.revenue)}</strong></p><p>Expenses: <strong>${money(row.expenses)}</strong></p></div><div class="report-totals"><p>Profit: <strong class="${row.profit<0?'negative':'positive'}">${money(row.profit)}</strong></p><p>Assets: <strong>${money(row.cash)}</strong></p></div>${row.bankrupt?`<p class="report-note">You don't have enough money left to stay in business. You're bankrupt!</p>`:''}${button('next-report',last?(game.day===DAYS?'See the final results':`Continue to Day ${game.day+1}`):`${escape(game.players[reportIndex+1].name)}'s stand`)}</section>`;
  $('#next-report').onclick=()=>{if(!last)beginReport(reportIndex+1);else if(game.day===DAYS)setPhase('results');else{game.day++;report=null;weather=null;void startWeather();}};
}
function renderResults(){
  const ranking=game.players.map((p,i)=>({...p,stand:i+1})).sort((a,b)=>b.cash-a.cash);
  const winners=ranking.filter(p=>p.cash===ranking[0].cash),names=joinNames(winners.map(p=>escape(p.name)));
  const title=winners.length===1?`${names} wins!`:`It's a tie!`;
  screen.innerHTML=`<section class="wide-screen results-screen"><span class="eyebrow">FOURTEEN DAYS IN ${words().town.toUpperCase()}</span><h1 class="winner-text">${title}</h1><p>${winners.length===1?names:`${names} finish joint first`} ${winners.length===1?'finishes':'with'} ${winners.length===1?'with ':''}<strong>${money(ranking[0].cash)}</strong>${winners.length>1?' each':''}.</p><div class="table-scroll"><table class="report-table"><thead><tr><th scope="col">Stand</th><th scope="col">Player</th><th scope="col">Glasses sold</th><th scope="col">Net profit</th><th scope="col">Final assets</th></tr></thead><tbody>${ranking.map(p=>`<tr><td>${p.stand}</td><th scope="row">${escape(p.name)}</th><td>${p.sold}</td><td class="${p.cash<economy().startingCash?'negative':'positive'}">${money(p.cash-economy().startingCash)}</td><td><strong>${money(p.cash)}</strong></td></tr>`).join('')}</tbody></table></div>${button('restart','Try again')}</section>`;
  $('#restart').onclick=resetGame;
}
$('#brand').onclick=event=>{event.preventDefault();$('#restart-dialog').showModal();};
$('#cancel-restart').onclick=()=>$('#restart-dialog').close();
$('#confirm-restart').onclick=resetGame;
$('#currency').onchange=event=>{if(game){event.target.value=currency;return;}currency=event.target.value;render();};
$('#language').onchange=event=>{if(phase!=='title'){event.target.value=language;return;}language=event.target.value;render();};
$('#sound').onclick=async()=>{const enabled=!music.enabled;if(enabled)music.enabled=true;else music.setEnabled(false);$('#sound').setAttribute('aria-pressed',String(enabled));$('#sound').innerHTML=`${enabled?'♫':'♪'} <span>Sound ${enabled?'on':'off'}</span>`;if(enabled){await music.unlock();if(music.enabled)music.setEnabled(true);}};
$('#help').onclick=()=>{if(isWeather())return;$('#help-rules').innerHTML=rulesMarkup();$('#help-dialog').showModal();};
document.querySelectorAll('.dialog-close').forEach(control=>control.onclick=()=>$('#help-dialog').close());
document.addEventListener('visibilitychange',()=>{if(document.hidden){gate?.pause();void music.pause();}else{gate?.resume();void music.resume();}gameBox.setAttribute('data-weather-paused',String(document.hidden));updateWeather();updateReport();});
render();
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  const tools=[{
    name:'read_lemonade_game',description:'Read public game state without exposing pending decisions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},
    execute(){return {phase,day:game?.day??null,currency,language,players:game?.players.map(({name,cash,bankrupt})=>({name,cash,bankrupt}))??[],forecast:weather?{type:weather.type,rainChance:weather.rainChance,roadworks:weather.roadworks}:null,activePlayer:phase==='planning'?playerIndex+1:null,reportPlayer:phase==='report'||phase==='report-wait'?reportIndex+1:null};}
  },{
    name:'submit_lemonade_plan',description:'Submit the active player’s plan. Price is in integer minor currency units. Only available during planning. The final player opens all stands.',inputSchema:{type:'object',properties:{glasses:{type:'integer',minimum:0,maximum:1000},signs:{type:'integer',minimum:0,maximum:50},price:{type:'integer',minimum:0,maximum:3000}},required:['glasses','signs','price'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},
    execute(input){if(phase!=='planning'||!game||game.players[playerIndex].bankrupt)throw new Error('No active player can submit a plan here.');if(!input||typeof input!=='object'||Object.keys(input).some(key=>!['glasses','signs','price'].includes(key)))throw new Error('Provide glasses, signs, and price only.');const error=validatePlan(input,game.players[playerIndex].cash,game.day,economy());if(error)throw new Error(error);const player=playerIndex+1;commitPlan({glasses:input.glasses,signs:input.signs,price:input.price});return {submitted:true,player,phase,day:game.day};}
  }];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

})();
