// Small dependency-free bundler. The checked-in app.js is ready for GitHub Pages.
import { readFile,writeFile } from 'node:fs/promises';
const modules=['economy.js','engine.js','audio.js','weather-gate.js','language.js','game-source.js'];
export async function bundleSource(){
  const parts=await Promise.all(modules.map(async file=>{
    const source=await readFile(new URL(file,import.meta.url),'utf8');
    return `// Source: ${file}\n`+source.replace(/^import\s+.*?;\s*$/gm,'').replace(/^export (?=(?:const|function|class)\b)/gm,'');
  }));
  return '// Generated by node build.js. Edit the source modules, then rebuild.\n(()=>{\n"use strict";\n'+parts.join('\n')+'\n})();\n';
}
const bundle=await bundleSource();
const scene=await readFile(new URL('scene.svg',import.meta.url),'utf8');
const outputs={'app.js':bundle,...Object.fromEntries(['hot','cloudy','storm'].map(type=>[`scene-${type}.svg`,scene.replace('<svg ',`<svg class="${type}" `)]))};
if(process.argv.includes('--check')){
  for(const [file,content] of Object.entries(outputs)) if(await readFile(new URL(file,import.meta.url),'utf8')!==content) throw new Error(`${file} is stale. Run npm run build.`);
  console.log('Published script and weather scenes match their sources.');
}else{for(const [file,content] of Object.entries(outputs)) await writeFile(new URL(file,import.meta.url),content);console.log('Built standalone app.js and three weather scenes.');}
